---
- project:
    templates:
      - check-requirements
      - openstack-python3-victoria-jobs
      - osc-tox-unit-tips
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - osc-functional-devstack:
            required-projects:
              - openstack/python-openstackclient
    gate:
      jobs:
        - osc-functional-devstack:
            required-projects:
              - openstack/python-openstackclient
