---
- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - osc-tox-unit-tips
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - osc-functional-devstack:
            required-projects:
              - openstack/python-openstackclient
        - osc-functional-devstack-tips:
            voting: false
            # The functional-tips job only tests the latest and shouldn't be run
            # on the stable branches
            branches: master
            required-projects:
              - openstack/python-openstackclient
    gate:
      jobs:
        - osc-functional-devstack:
            required-projects:
              - openstack/python-openstackclient
